
# Default values for permissions
DEFAULT_SETTINGS = {
    "IRANIAN_CITIES_ADMIN_ADD_READONLY_ENABLED": True,
    "IRANIAN_CITIES_ADMIN_DELETE_READONLY_ENABLED": True,
    "IRANIAN_CITIES_ADMIN_CHANGE_READONLY_ENABLED": True,
}
