from typing import Dict

# Default values for permissions
DEFAULT_SETTINGS: Dict[str, bool] = {
    "IRANIAN_CITIES_ADMIN_ADD_READONLY_ENABLED": False,
    "IRANIAN_CITIES_ADMIN_DELETE_READONLY_ENABLED": False,
    "IRANIAN_CITIES_ADMIN_CHANGE_READONLY_ENABLED": False,
    "IRANIAN_CITIES_ADMIN_INLINE_ENABLED": False,
}
