# Generated by Django 5.0.7 on 2024-07-24 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iranian_cities", "0005_auto_20221004_0004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="iranian_cities.province",
                verbose_name="Province",
            ),
        ),
        migrations.AlterField(
            model_name="county",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counties",
                to="iranian_cities.province",
                verbose_name="Province",
            ),
        ),
    ]
