# Generated by Django 5.0.7 on 2024-07-25 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iranian_cities", "0008_alter_city_options_alter_county_options_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="city",
            new_name="sage_city_code_8db749_idx",
            old_name="iranian_cit_code_1c3b38_idx",
        ),
        migrations.RenameIndex(
            model_name="county",
            new_name="sage_county_code_d341c3_idx",
            old_name="iranian_cit_code_7732af_idx",
        ),
        migrations.RenameIndex(
            model_name="district",
            new_name="sage_distri_code_51960b_idx",
            old_name="iranian_cit_code_5e016c_idx",
        ),
        migrations.RenameIndex(
            model_name="province",
            new_name="sage_provin_code_e8a53f_idx",
            old_name="iranian_cit_code_3fe5d7_idx",
        ),
        migrations.RenameIndex(
            model_name="ruraldistrict",
            new_name="sage_rural__code_6a6b70_idx",
            old_name="iranian_cit_code_39b229_idx",
        ),
        migrations.RenameIndex(
            model_name="village",
            new_name="sage_villag_code_3ebc50_idx",
            old_name="iranian_cit_code_358568_idx",
        ),
        migrations.AlterModelTable(
            name="city",
            table="sage_city",
        ),
        migrations.AlterModelTable(
            name="county",
            table="sage_county",
        ),
        migrations.AlterModelTable(
            name="district",
            table="sage_district",
        ),
        migrations.AlterModelTable(
            name="province",
            table="sage_province",
        ),
        migrations.AlterModelTable(
            name="ruraldistrict",
            table="sage_rural_district",
        ),
        migrations.AlterModelTable(
            name="village",
            table="sage_village",
        ),
    ]
